### ISSUE TITLE
[Bug]: Update breaks plugin

### ISSUE THREAD

**Issue by NomarCub** [chrisgrieser/new-tab-default-page#17]
### Bug Description

The update breaks the plugin. Pressing the update button failed, then after uninstalling it, it fails to install anew at all.

### Relevant Screenshot

![image](https://github.com/chrisgrieser/new-tab-default-page/assets/5298006/c0103d0f-5f15-4319-bc2e-52c2cc2a8f5d)

### Obsidian Version

1.3.7

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
which update? the plugin did not have any update for months?
<img width="312" alt="Pasted image 2023-08-07 at 18 15 42@2x" src="https://github.com/chrisgrieser/new-tab-default-page/assets/73286100/0fe31cd4-3935-4d36-a150-de614ba618af">

I'm going to assume that this was rather a problem with your internet connection or with GitHub?

Anyway, whatever the cause, since there hasn't been any update, seems like this isn't an issue with this plugin.

**Comment by NomarCub** [comment]
It's probably some bug in the Obsidian plugin install mechanism then. I'm not sure what caused it, I can install other plugins fine, but can't install this one still, even from the sandbox vault. Dunno why it found an update either. I'll post here, if I find something out, maybe others could find it helpful.

**Comment by chrisgrieser** [comment]
oh, I see, my bad, it seems a contributor edited the `manifest.json` file, changing version requirements. (reference: https://github.com/chrisgrieser/new-tab-default-page/commit/c4beecf171ebb8585f5e24716f29d73fe5d80ae4)

I just fixed the issue, you should now be able to install the plugin again.
