### ISSUE TITLE
Feature Request: Compatability with Periodic Notes for Daily note

### ISSUE THREAD

**Issue by jloh** [chrisgrieser/new-tab-default-page#4]
### Feature Requested

I use Periodic Notes instead of the default daily notes plugin so I can get weekly and monthly notes as well. It would be awesome if this plugin extended its functionality to support daily notes supplied by Periodic Notes as well!

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Should be possible.

Since I do not use the Periodic Notes plugin myself, is there a particular command to open the current week note or something? The New Tab Page plugin essentially just runs certain commands when it detects that a new tab has been opened, so if there is a static command from the periodic notes plugin, that should be an easy addition

**Comment by jloh** [comment]
There is, yeah. Its designed to be a drop in replacement for the standard daily notes more or less. I'm unsure how to get the command IDs for you, is there an easy way? Heres a screenshot of the command pallet at least 😅 

<img width="694" alt="image" src="https://user-images.githubusercontent.com/3689532/195720102-d4cdc956-56fa-44d9-b29b-61ebfec0bc22.png">

**Comment by chrisgrieser** [comment]
great, added in the latest release. 😊
